### ISSUE TITLE
The 'hashMethod' Parameter

### ISSUE THREAD

**Issue by CafeAuLait-CC** [imink-app/f-API#1]
Hello,

It seems that when calling the f-API at `https://api.imink.app/f`, the parameter is named as `hashMethod`, but in the released apk version(v1.0.2) for local deployment, this parameter is called `hash_method`. 

Could you please update the apk package to make the parameter name matches?

**Comment by JoneWang** [comment]
Request `https://api.imink.app/f` must also use `hash_method`. `hashMethod` is a bug on the server.
