### ISSUE TITLE
Step2 F-token generation appears to be broken with 2.5.1

### ISSUE THREAD

**Issue by mcat1997** [imink-app/f-API#3]
As title states, Nintendo must have changed the Step2 F-API with release 2.5.1. Attempting to login under[https://api-lp1.znc.srv.nintendo.net/v2/Game/GetWebServiceToken] throws a 9403 (Invalid token) error.

**Comment by Coxxs** [comment]
I believe they have been preparing this since at least March (when 2.5.0 was released), the "check" for unofficial apps has been added since then.
A temporary fix: https://github.com/Coxxs/NSOk

**Comment by StarlightC** [comment]
It seems that they use [FCM Token](https://firebase.google.com/docs/cloud-messaging/android/client) instead.

**Comment by JoneWang** [comment]
Fixed
