### ISSUE TITLE
Wrong token with 2.9.0 version

### ISSUE THREAD

**Issue by nazarii-semeniuk** [imink-app/f-API#4]
Hi, is it working with 2.9.0 version? For now, I can't use lower version because I'm receiving "Upgrade required" error, but when I'm switching to 2.9.0 version in headers, I'm receiving 9403 error - "Invalid token".

**Comment by JoneWang** [comment]
@nazarii-semeniuk 
Are you sending the request to https://api.imink.app/f? Currently, it only works with 2.9.0.
I just tested it. It works fine.

**Comment by JoneWang** [comment]
imink f api has now been updated to version 2.10.0.

**Comment by nazarii-semeniuk** [comment]
Sorry, that was my fault.

**Comment by nazarii-semeniuk** [comment]
Everything is working, I was sending wrong token (access instead of id).
