### ISSUE TITLE
F-token generation appears to be broken

### ISSUE THREAD

**Issue by liopoos** [imink-app/f-API#5]
I tried to request the API, but it returned an error:
```
{"reason":"Something went wrong.","error":true}
```

My request body: 
```
{
  "token": "xxx",
  "hash_method": "1"
}
```

**Comment by JoneWang** [comment]
fixed

**Comment by liopoos** [comment]
Unfortunately, f api seems to have stopped working again.

**Comment by JoneWang** [comment]
> Unfortunately, f api seems to have stopped working again.

Nintendo updated their app and now can't get the f properly. recovery time can't be determined.

**Comment by Caier** [comment]
> > Unfortunately, f api seems to have stopped working again.
> 
> Nintendo updated their app and now can't get the f properly. recovery time can't be determined.

~~Sorry for bumping, but could you maybe guide me to any information about what exactly has changed in the latest version of the app that prohibits the f API from working? Is it the anti-debugger measures or something else entirely?~~

Yep, there was a discussion on https://discord.com/invite/4D82rFkXRv. The main problem introduced in this update is the tight integration of the app with Play Integrity API, the anti-debugger checks that break tools like frida and one of the authorization endpoints requiring the integrity token from the google API (this one is not yet enforced apparently though).
